### ISSUE TITLE
最新代码 bazel编译出错

### ISSUE THREAD

**Issue by samaritan1998** [alibaba/rtp-llm#126]
ERROR: /root/.cache/bazel/_bazel_root/bff503829302c40910a248598482644e/external/rules_python/python/private/common/py_executable.bzl:886:12: name 'RunEnvironmentInfo' is not defined
ERROR: error loading package '': at /home/rtp-llm/deps/pip.bzl:1:6: at /root/.cache/bazel/_bazel_root/bff503829302c40910a248598482644e/external/rules_python/python/pip.bzl:25:6: at /root/.cache/bazel/_bazel_root/bff503829302c40910a248598482644e/external/rules_python/python/private/pypi/pip_compile.bzl:22:6: at /root/.cache/bazel/_bazel_root/bff503829302c40910a248598482644e/external/rules_python/python/defs.bzl:17:6: at /root/.cache/bazel/_bazel_root/bff503829302c40910a248598482644e/external/rules_python/python/py_binary.bzl:20:6: at /root/.cache/bazel/_bazel_root/bff503829302c40910a248598482644e/external/rules_python/python/private/common/py_binary_macro_bazel.bzl:17:6: at /root/.cache/bazel/_bazel_root/bff503829302c40910a248598482644e/external/rules_python/python/private/common/py_binary_rule_bazel.bzl:19:5: at /root/.cache/bazel/_bazel_root/bff503829302c40910a248598482644e/external/rules_python/python/private/common/py_executable_bazel.bzl:32:5: compilation of module 'python/private/common/py_executable.bzl' failed
INFO: Elapsed time: 0.099s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

bazel version: 5.2.0  代码是最新提交的版本（想用下classifier的功能）

**Comment by samaritan1998** [comment]
尝试升级bazel版本 之后又报其他的错 Could not find any nccl.h matching version '2' in any subdirectory: ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'
of:
        '/usr/local/cuda/'
ERROR: no such package '@@local_config_cudacuda': Repository command failed
Could not find any nccl.h matching version '2' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
        'local/cuda/extras/CUPTI/include'  可以帮忙看看嘛

**Comment by baowendin** [comment]
最新代码需要用bazelisk，使用方法和bazel一致，但是升级bazel到6.4.0按说也行。后面的报错看着像不在gpu容器里编译，/usr/local/cuda/include目录下应该是有nccl.h的

**Comment by samaritan1998** [comment]
okk 我再试下 感谢~~

**Comment by samaritan1998** [comment]
![image](https://github.com/user-attachments/assets/e7687966-0385-4ed2-820e-868b51933bbb)
有这个文件诶  请问可以发下最新的镜像么？

**Comment by samaritan1998** [comment]
> 嗯，我们近期会发布一个比较大的更新，所以还需要一点时间

请问大概是什么时间点呀？
