### ISSUE TITLE
能否提供do_sample=False的选项,在function_call和代码生成领域比较需要.

### ISSUE THREAD

**Issue by invisifire** [alibaba/rtp-llm#16]
在生成结果时不进行随机采样, 不对token 的logistics进行分布转换,直接选出最高概率的token

**Comment by xinfeishi** [comment]
那直接使用top_k=1,top_p=0, 也能完成这个意图。

**Comment by invisifire** [comment]
试过了不可以,生成结果有区别

**Comment by invisifire** [comment]
> 那直接使用top_k=1,top_p=0, 也能完成这个意图。

不可以,试过了, 因为tempreture的原因答案不固定

**Comment by invisifire** [comment]
![image](https://github.com/alibaba/rtp-llm/assets/59678894/bc6c1572-f653-4aa0-bac9-33d50858a936)
可以看一下 TOPk =1 top_p和temperature为默认值, 总会有不一样的答案无法稳定复现

**Comment by ySingularity** [comment]
可以试着打印一下logits看看？
