### ISSUE TITLE
[Bug] Qwen-7B-Chat coredump

### ISSUE THREAD

**Issue by zhyncs** [alibaba/rtp-llm#17]
Hi @LLLLKKKK @xinfeishi @dongjiyingdjy May you help fix this issue? Thanks.

### environment
```
rtp-llm: maga_transformer-0.1.3+cuda118-cp310-cp310-manylinux1_x86_64.whl
Qwen-7B-Chat: https://huggingface.co/Qwen/Qwen-7B-Chat

sys.platform: linux
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
GPU 0: NVIDIA A100-SXM4-80GB
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.8, V11.8.89
GCC: gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
PyTorch: 2.1.0+cu118
transformers: 4.33.1
```

### execution
```bash
export TOKENIZER_PATH=/workdir/Qwen-7B-Chat
export CHECKPOINT_PATH=/workdir/Qwen-7B-Chat
export FT_SERVER_TEST=1
export GUARANTE_GENERATE_MEM=1
export WEIGHT_TYPE=fp16
export INT8_KV_CACHE=0
python3 -m maga_transformer.start_server
```

### traceback
```
[root][02/05/2024 10:45:49][__init__.py:<module>():15][INFO] init logger end
Segmentation fault (core dumped)
```

The default Python on the server is 3.9, because rtp-llm only provides Python 3.10 packages, so I used miniconda to install the Python 3.10 environment. I am not sure whether this is related. If so, I hope rtp-llm can provide Python 3.9 package, maybe you can use GitHub action workflow.

Since I don’t have a lot of time to constantly try and solve this issue of rtp-llm in this environment. Maybe this requires you to continue to follow up. Thanks.

**Comment by zhyncs** [comment]
Since I haven’t received a reply for too long, maybe your work focus is not on maintaining open source projects. I will close this issue first. If you have any progress in the future, you are welcome to reopen this issue or leave a message below.

**Comment by xinfeishi** [comment]
> Hi @LLLLKKKK @xinfeishi @dongjiyingdjy May you help fix this issue? Thanks.
> 
> ### environment
> ```
> rtp-llm: maga_transformer-0.1.3+cuda118-cp310-cp310-manylinux1_x86_64.whl
> Qwen-7B-Chat: https://huggingface.co/Qwen/Qwen-7B-Chat
> 
> sys.platform: linux
> Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
> CUDA available: True
> GPU 0: NVIDIA A100-SXM4-80GB
> CUDA_HOME: /usr/local/cuda
> NVCC: Cuda compilation tools, release 11.8, V11.8.89
> GCC: gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
> PyTorch: 2.1.0+cu118
> transformers: 4.33.1
> ```
> 
> ### execution
> ```shell
> export TOKENIZER_PATH=/workdir/Qwen-7B-Chat
> export CHECKPOINT_PATH=/workdir/Qwen-7B-Chat
> export FT_SERVER_TEST=1
> export GUARANTE_GENERATE_MEM=1
> export WEIGHT_TYPE=fp16
> export INT8_KV_CACHE=0
> python3 -m maga_transformer.start_server
> ```
> 
> ### traceback
> ```
> [root][02/05/2024 10:45:49][__init__.py:<module>():15][INFO] init logger end
> Segmentation fault (core dumped)
> ```
> 
> The default Python on the server is 3.9, because rtp-llm only provides Python 3.10 packages, so I used miniconda to install the Python 3.10 environment. I am not sure whether this is related. If so, I hope rtp-llm can provide Python 3.9 package, maybe you can use GitHub action workflow.
> 
> Since I don’t have a lot of time to constantly try and solve this issue of rtp-llm in this environment. Maybe this requires you to continue to follow up. Thanks.

can you show the detail backtrace of core dump?

**Comment by zhyncs** [comment]
> > Hi @LLLLKKKK @xinfeishi @dongjiyingdjy May you help fix this issue? Thanks.
> > ### environment
> > ```
> > rtp-llm: maga_transformer-0.1.3+cuda118-cp310-cp310-manylinux1_x86_64.whl
> > Qwen-7B-Chat: https://huggingface.co/Qwen/Qwen-7B-Chat
> > 
> > sys.platform: linux
> > Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
> > CUDA available: True
> > GPU 0: NVIDIA A100-SXM4-80GB
> > CUDA_HOME: /usr/local/cuda
> > NVCC: Cuda compilation tools, release 11.8, V11.8.89
> > GCC: gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
> > PyTorch: 2.1.0+cu118
> > transformers: 4.33.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### execution
> > ```shell
> > export TOKENIZER_PATH=/workdir/Qwen-7B-Chat
> > export CHECKPOINT_PATH=/workdir/Qwen-7B-Chat
> > export FT_SERVER_TEST=1
> > export GUARANTE_GENERATE_MEM=1
> > export WEIGHT_TYPE=fp16
> > export INT8_KV_CACHE=0
> > python3 -m maga_transformer.start_server
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### traceback
> > ```
> > [root][02/05/2024 10:45:49][__init__.py:<module>():15][INFO] init logger end
> > Segmentation fault (core dumped)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The default Python on the server is 3.9, because rtp-llm only provides Python 3.10 packages, so I used miniconda to install the Python 3.10 environment. I am not sure whether this is related. If so, I hope rtp-llm can provide Python 3.9 package, maybe you can use GitHub action workflow.
> > Since I don’t have a lot of time to constantly try and solve this issue of rtp-llm in this environment. Maybe this requires you to continue to follow up. Thanks.
> 
> can you show the detail backtrace of core dump?

This traceback is complete now. Maybe when you bump a new release with Python 3.9, I will consider continuing to try it. Thanks.

**Comment by xinfeishi** [comment]
> > > Hi @LLLLKKKK @xinfeishi @dongjiyingdjy May you help fix this issue? Thanks.
> > > ### environment
> > > ```
> > > rtp-llm: maga_transformer-0.1.3+cuda118-cp310-cp310-manylinux1_x86_64.whl
> > > Qwen-7B-Chat: https://huggingface.co/Qwen/Qwen-7B-Chat
> > > 
> > > sys.platform: linux
> > > Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
> > > CUDA available: True
> > > GPU 0: NVIDIA A100-SXM4-80GB
> > > CUDA_HOME: /usr/local/cuda
> > > NVCC: Cuda compilation tools, release 11.8, V11.8.89
> > > GCC: gcc (GCC) 8.3.1 20190311 (Red Hat 8.3.1-3)
> > > PyTorch: 2.1.0+cu118
> > > transformers: 4.33.1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### execution
> > > ```shell
> > > export TOKENIZER_PATH=/workdir/Qwen-7B-Chat
> > > export CHECKPOINT_PATH=/workdir/Qwen-7B-Chat
> > > export FT_SERVER_TEST=1
> > > export GUARANTE_GENERATE_MEM=1
> > > export WEIGHT_TYPE=fp16
> > > export INT8_KV_CACHE=0
> > > python3 -m maga_transformer.start_server
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ### traceback
> > > ```
> > > [root][02/05/2024 10:45:49][__init__.py:<module>():15][INFO] init logger end
> > > Segmentation fault (core dumped)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > The default Python on the server is 3.9, because rtp-llm only provides Python 3.10 packages, so I used miniconda to install the Python 3.10 environment. I am not sure whether this is related. If so, I hope rtp-llm can provide Python 3.9 package, maybe you can use GitHub action workflow.
> > > Since I don’t have a lot of time to constantly try and solve this issue of rtp-llm in this environment. Maybe this requires you to continue to follow up. Thanks.
> > 
> > 
> > can you show the detail backtrace of core dump?
> 
> This traceback is complete now. Maybe when you bump a new release with Python 3.9, I will consider continuing to try it. Thanks.

it's not easy to provider python3.9 whl, it cost much time.No plans yet。

**Comment by xinfeishi** [comment]
can you try the docker env? it's very clean and easy to use.

**Comment by zhyncs** [comment]
> can you try the docker env? it's very clean and easy to use.

The company's container environment is limited, which is not very convenient.

**Comment by zhyncs** [comment]
> @zhyncs 可以贴一下gdb堆栈吗

My docker test environment has been destroyed, but I think this is very easy to reproduce, you can refer to https://github.com/alibaba/rtp-llm/issues/17#issue-2117619789

**Comment by zhyncs** [comment]
> it's not easy to provider python3.9 whl, it cost much time.No plans yet

If rtp-llm wants to be widely promoted in the community, supporting multiple versions of Python and CUDA is necessary. If you don’t have a plan to promote it in the community, it doesn't have much impact. Thanks.
