### ISSUE TITLE
缺少文件：libth_transformer.so

### ISSUE THREAD

**Issue by toyZhangxinjie** [alibaba/rtp-llm#18]
rtp-llm/maga_transformer/libs/libth_transformer.so: cannot open shared object file: No such file or directory

**Comment by frankang** [comment]
换一个目录启动就可以了，不要在rtp-llm目录启动服务，否则会调用本地的maga_transformer目录内容。
看看官方有什么更好启动建议？

**Comment by toyZhangxinjie** [comment]
@frankang 多谢大佬，可以了
