### ISSUE TITLE
NameError: name 'Middleware'is not defined, Did you mean: 'CoRsMiddleware'?

### ISSUE THREAD

**Issue by zzhdbw** [alibaba/rtp-llm#22]
2024-03-01

按照readme的方式装完环境后，执行命令如下
CUDA_VISIBLE_DEVICES=0 MODEL_TYPE=qwen_7b TOKENIZER_PATH=/home/models/Qwen/qwen-7b-chat/ CHECKPOINT_PATH=/home/models/Qwen/qwen-7b-chat/ FT_SERVER_TEST=1 python3 -m maga_transformer.start_server

报错如下：
<img width="1219" alt="7cd1bd3fd6e3b72b65aedf4924071e0" src="https://github.com/alibaba/rtp-llm/assets/38305980/5426cde4-4ed0-45a3-b0ec-a8ec47071d14">

翻看maga-transformers源码发现start_server.py 中的Middleware确实没有引入，如图所示：

<img width="461" alt="e3991eb6ab6bd613271fa7b9d47e0e6" src="https://github.com/alibaba/rtp-llm/assets/38305980/8cfebf3c-840e-4cc5-b292-6982112cb52b">
<img width="625" alt="4184935d8fd4ed4cd6b04ff82ea81f6" src="https://github.com/alibaba/rtp-llm/assets/38305980/4116289e-49ec-400a-9e98-858465dc0db1">

maga-transformers版本是v0.1.4

请问是我的环境问题吗

**Comment by xinfeishi** [comment]
中间版本确实有点问题了，现在最新版本应该可以了吧。
