### ISSUE TITLE
BUG: MISSING QUOTATION MARKS AND LINE BREAKS

### ISSUE THREAD

**Issue by invisifire** [alibaba/rtp-llm#29]
When using the server-wrapped OpenAI format for chat, compared to generate, it may result in randomly missing quotation marks and line breaks in the generated content.

I tried both the Qwen and Deepseek models, and encountered the same phenomenon. Additionally, with the same input, the outputs from the "chat" and "generate" interfaces only differ in terms of line breaks, with "chat" consistently missing.
Here is an example.
![image](https://github.com/alibaba/rtp-llm/assets/59678894/fd4b3cc3-898b-46c4-89a6-066b1098175b)

I ensure the input format is completely consistent, and the generated parameters are completely consistent.

**Comment by dongjiyingdjy** [comment]
你可以尝试一下增加一些debug代码来比对两种输入的logits吗？

**Comment by invisifire** [comment]
> 你可以尝试一下增加一些debug代码来比对两种输入的logits吗？
抽空把, 没搞项目的编译环境 ,直接用的pip包没法改server 的openai接口源码
