### ISSUE TITLE
bazel编译失败

### ISSUE THREAD

**Issue by yuhui-xie** [alibaba/rtp-llm#33]
执行bazel build //maga_transformer:maga_transformer --jobs 100 --verbose_failures的时候失败：
之前按照doc下面build.md做的，安装了python相关的依赖。
请问可以怎么解决吗

`root@ostname:/home/user/rtp-llm# bazel build //maga_transformer:maga_transformer --jobs 100 --verbose_failures
INFO: Repository pip_gpu_torch instantiated at:
  /home/user/rtp-llm/WORKSPACE:16:9: in <toplevel>
  /home/user/rtp-llm/deps/pip.bzl:4:16: in pip_deps
  /root/.cache/bazel/_bazel_root/ba25e3f7c8d8f2d38c56579ba352ed74/external/rules_python/python/pip.bzl:53:19: in pip_install
Repository rule pip_repository defined at:
  /root/.cache/bazel/_bazel_root/ba25e3f7c8d8f2d38c56579ba352ed74/external/rules_python/python/pip_install/pip_repository.bzl:69:33: in <toplevel>
INFO: Repository pip_gpu_cuda12_torch instantiated at:
 /home/user/rtp-llm/WORKSPACE:16:9: in <toplevel>
 /home/user/rtp-llm/deps/pip.bzl:10:16: in pip_deps
  /root/.cache/bazel/_bazel_root/ba25e3f7c8d8f2d38c56579ba352ed74/external/rules_python/python/pip.bzl:53:19: in pip_install
Repository rule pip_repository defined at:
  /root/.cache/bazel/_bazel_root/ba25e3f7c8d8f2d38c56579ba352ed74/external/rules_python/python/pip_install/pip_repository.bzl:69:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'pip_gpu_torch':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/ba25e3f7c8d8f2d38c56579ba352ed74/external/rules_python/python/pip_install/pip_repository.bzl", line 65, column 13, in _pip_repository_impl
                fail("rules_python_external failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python_external failed:  (Timed out)
ERROR: /home/user/rtp-llm/WORKSPACE:16:9: fetching pip_repository rule //external:pip_gpu_torch: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/ba25e3f7c8d8f2d38c56579ba352ed74/external/rules_python/python/pip_install/pip_repository.bzl", line 65, column 13, in _pip_repository_impl
                fail("rules_python_external failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python_external failed:  (Timed out)
ERROR: Skipping '//maga_transformer:maga_transformer': no such package '@pip_gpu_torch//': rules_python_external failed:  (Timed out)
WARNING: Target pattern parsing failed.
ERROR: no such package '@pip_gpu_torch//': rules_python_external failed:  (Timed out)
INFO: Elapsed time: 600.904s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: maga_transformer`

**Comment by ySingularity** [comment]
下载依赖超时 可以改个源试试？
在open_source/deps/pip.bzl配置extra_pip_args=["--index_url=xxx"]
