### ISSUE TITLE
最新whl包无法启动server

### ISSUE THREAD

**Issue by frankang** [alibaba/rtp-llm#35]
两个bug
1. 最新whl 0.1.7 版无法启动server，报错
`ModuleNotFoundError: No module named 'maga_transformer.model_factory'` , 发现是whl包路径下缺`model_factory.py`文件`, 拜托后面发包的时候做一下是否能正常启动的检查

2. 请求generate_config里面的`return_input_ids`和`return_output_ids`参数未能生效， 未返回这两个值。
  下面是测试的generate_config: `"generate_config": {"max_new_tokens": 40, "repetition_penalty": 1, "num_beams": 1, "temperature": 1, "random_seed": 1234, "using_hf_sampling": true, "num_return_sequences": 1, "calculate_loss": 0, "yield_generator": false, "return_incremental": false, "max_new_tokens": 100, "return_input_ids": true, "request_format": "raw", "return_output_ids": true}`

**Comment by ySingularity** [comment]
1. 感谢反馈 我们稍后更一下新包
2. 能提供一下测试场景吗 例如模型、请求、以及相关log

**Comment by frankang** [comment]
> 1. 感谢反馈 我们稍后更一下新包      已更新
> 2. 能提供一下测试场景吗 例如模型、请求、以及相关log

测试应该是在请求里面提供num_return_sequences参数后出的问题（即使设置为1也有），return_input_ids、return_logits/output_logits 等参数无法作用。不设置它能够返回这些结果。

**Comment by ySingularity** [comment]
> 测试应该是在请求里面提供num_return_sequences参数后出的问题（即使设置为1也会发生问题），return_input_ids、return_logits/output_logits 等参数无法作用。不设置它能够返回这些结果。

现在的实现逻辑是这样的，走num return sequences是不会组装output/input id，如果有这个需求会进行更新

**Comment by frankang** [comment]
> 
> 现在的实现逻辑是这样的，走num return sequences是不会组装output/input id，如果有这个需求会进行更新

好的，暂时没有这个需求。请问num_return_sequences=1时的推理逻辑是否会和不指定此参数时一致？
其实还是比较希望random_seed能够早日支持

**Comment by ySingularity** [comment]
> 请问num_return_sequences=1时的推理逻辑是否会和不指定此参数时一致？

不会
