### ISSUE TITLE
怎么使用qwen medusa推理加速

### ISSUE THREAD

**Issue by BucherLi** [alibaba/rtp-llm#37]
能否提供一个medusa推理加速的例子

**Comment by baowendin** [comment]
qwen训练方式可以参考medusa github仓库的文档，需要修改modeling_qwen.py。测试的话medusa仓库里有vicuna medusa huggingface链接，按照SpeculativeDecoding-Tutroial.md里补充config.json和基座模型的checkpoint也可运行

**Comment by Grant-Rk** [comment]
请问千问用medusa训练后 mc_sim_7b_63可以正常解码吗还是应该用别的medusa_choices
