### ISSUE TITLE
主页里的"PTuning使用文档"链接不存在

### ISSUE THREAD

**Issue by codelast** [alibaba/rtp-llm#4]
![ptuning_doc_missing](https://github.com/alibaba/rtp-llm/assets/2604170/7b97dc7d-1992-4ad5-a684-09110d7d9164)

**点进去是这样：**

![ptuning_doc_missing_2](https://github.com/alibaba/rtp-llm/assets/2604170/685612d8-7a64-4ad2-b591-866be3088819)

**Comment by xinfeishi** [comment]
我看下这个问题。
