### ISSUE TITLE
Poor performance at batchsize=1 on V100

### ISSUE THREAD

**Issue by cwlseu** [alibaba/rtp-llm#40]
我在v100上使用相同的测试数据，相同的并发数量测试 vicuna-7B 发现：
1. batchsize=1 的时候， rtpllm的token生成吞吐是vllm的70～89%
2. batchsize>=2的时候， rtpllm的token生成吞吐是vllm的110%
如下图所示
![Vicuna-7B LLM and RTP-LLM Performance on V100(genlen=64)](https://github.com/alibaba/rtp-llm/assets/5145788/61d85f0c-c6e0-4464-b019-ba6a3853dce8)

问题：
- 上述结果跟你们的v100上是一致的吗？feature中介绍的在v100上的优化是做了什么，感觉时间延迟更长了。
- 公布的performance中为在A10上的Qwen-7B-Chat的性能，rtpllm的性能是vllm的1.5倍左右。这个优化提升是针对 Qwen 定制优化的吗？为什么差这么多？

**Comment by dongjiyingdjy** [comment]
对于V100上的测试，相比vLLM，我们的可能优势在于：
1. 我们使用了trt-llm的V100 fmha（在release 0.1.7以后enable），在长seq时可以明显加速和降低显存占用；
2. 我们当前广泛使用weight only int8 quant（W8A16), 除了降低显存占用外，在decode阶段可以明显降低延时，而在prefill阶段，当input length较长时，可能会性能弱于fp16。我们的V100优化指的是小batch时的WOQ kernel优化。
我们对qwen没有定制优化逻辑，在qwen上的测试结果和llama系列模型(meta-llama/Llama-2-7b, meta-llama/Llama-2-13b-hf, meta-llama/Llama-2-70b-hf, lmsys/vicuna-33b-v1.3, 01-ai/Yi-34B, xverse/XVERSE-13B, etc.）应该是保持一致的。
你可以进一步解释你的测试方式和指标吗？包含input length，测试脚本，qps的含义？

**Comment by dongjiyingdjy** [comment]
> ## 测试指标解释
> QPS: 每秒钟处理的text个数 Token QPS： 每秒钟生成的token数目
> 
> ## 测试模型：
> * Mistral-7B： https://huggingface.co/HuggingFaceH4/zephyr-7b-beta
> * Vicuna-7B: https://huggingface.co/lmsys/vicuna-7b-v1.5
> 
> ## 测试硬件： Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz + 单卡 NVIDIA V100
> ## 输入输出
> * 输入长度： 平均token长度为 710
> * 生成长度： 64, 128, 256
> * 测试脚本：[locust_test_default.py.zip](https://github.com/alibaba/rtp-llm/files/14832734/locust_test_default.py.zip)
>   `locust -f ./locust_test_default.py --host=http://127.0.0.1:8088 -u 1 r 1 -t 300 --headless --only-summary --output_len=[64,128,256]`

感觉你的解释！
根据给出的测试条件，rtp-llm与vllm的性能测试结果接近是符合预期的；在batch=1稍差的问题会在c++重构后解决。
如果希望获得更好的性能收益，我们推荐在短seq时开启weight only int8量化，可以获得显著的性能提升；当seq较大时，我们支持的FMHA也会明显加速prefill阶段。
weight only int8量化和FMHA均可能会带来精度损失，但在我们的测试下，大部分情况下都不会影响结果生成。

**Comment by dongjiyingdjy** [comment]
补充：说符合逻辑是因为在fp16且seq不长时，在latency中占比最大的matmul都会调用[cublas](https://docs.nvidia.com/cuda/cublas/)，而其他kernel由于时间占比小，对性能影响相对较小；而小并发屏蔽了框架间调度能力的差异。在这种条件下，各框架的性能应该都会比较接近。
此外，传入有效的cublas gemm algo对于pre-ampere在调用cublas时的性能提升帮助较大。

**Comment by cwlseu** [comment]
weight only int8 是指直接在环境变量中设置`WEIGH_TYPE=int8`吗？还是其他什么用法？
根据你们的经验，使用weightonlyint8的话，相比较fp16性能会损失多少？

**Comment by dongjiyingdjy** [comment]
> weight only int8 是指直接在环境变量中设置`WEIGH_TYPE=int8`吗？还是其他什么用法？ 根据你们的经验，使用weightonlyint8的话，相比较fp16性能会损失多少？

INT8_MODE=1 或 WEIGHT_TYPE=int8；
大部分情况下对模型表现力影响较小。

**Comment by cwlseu** [comment]
测了一下 batchsize=1，2 的时候，weight only int8的收益不是很明显。V100 上做 INT8 应该性能增益不大。
![RTPLLM Token Generation Performance ](https://github.com/alibaba/rtp-llm/assets/5145788/f1857919-ccd3-4bb5-84b8-86b39108febd)

**Comment by dongjiyingdjy** [comment]
> 测了一下 batchsize=1，2 的时候，weight only int8的收益不是很明显。V100 上做 INT8 应该性能增益不大。 ![RTPLLM Token Generation Performance ](https://private-user-images.githubusercontent.com/5145788/318746239-f1857919-ccd3-4bb5-84b8-86b39108febd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTc4NDQsIm5iZiI6MTcxMjA1NzU0NCwicGF0aCI6Ii81MTQ1Nzg4LzMxODc0NjIzOS1mMTg1NzkxOS1jY2QzLTRiYjUtODRiOC04NmIzOTEwOGZlYmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDJUMTEzMjI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDUxZDQ2ZTgzMzQyNTExZmFlMTI3ZjNjNjQ4MTk3ZmI0OTc0NjhiODJiY2U5YjYwYjI1YmM0M2JlYTM0ZmM4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JeT-gbJz7CWMo8idwfpMs3deaCukT7GevjMTmz4yYH0)

随着output token增大，int8的性能优势会更加明显。

**Comment by samaritan1998** [comment]
请问一下这里的BatchSize是怎么控制的呢？

**Comment by dongjiyingdjy** [comment]
@cwlseu 你好，最近验证发现这个版本V100确实存在比较严重的性能问题，我们在本周将会release的0.1.13中已修复，欢迎在本周release后使用

**Comment by zerozw** [comment]
@cwlseu 0.1.13中已fix

**Comment by zerozw** [comment]
fixed
