### ISSUE TITLE
bazel构建失败

### ISSUE THREAD

**Issue by samaritan1998** [alibaba/rtp-llm#42]
INFO: Repository pip_gpu_cuda12_torch instantiated at:
  /home/WORKSPACE:16:9: in <toplevel>
  /home/deps/pip.bzl:11:16: in pip_deps
  /root/.cache/bazel/_bazel_root/f93b59b2e8d1062ff73145ba826f8efd/external/rules_python/python/pip.bzl:53:19: in pip_install
Repository rule pip_repository defined at:
  /root/.cache/bazel/_bazel_root/f93b59b2e8d1062ff73145ba826f8efd/external/rules_python/python/pip_install/pip_repository.bzl:69:33: in <toplevel>
INFO: Repository pip_gpu_torch instantiated at:
  /home/WORKSPACE:16:9: in <toplevel>
  /home/deps/pip.bzl:4:16: in pip_deps
  /root/.cache/bazel/_bazel_root/f93b59b2e8d1062ff73145ba826f8efd/external/rules_python/python/pip.bzl:53:19: in pip_install
Repository rule pip_repository defined at:
  /root/.cache/bazel/_bazel_root/f93b59b2e8d1062ff73145ba826f8efd/external/rules_python/python/pip_install/pip_repository.bzl:69:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'pip_gpu_cuda12_torch':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/f93b59b2e8d1062ff73145ba826f8efd/external/rules_python/python/pip_install/pip_repository.bzl", line 65, column 13, in _pip_repository_impl
                fail("rules_python_external failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python_external failed:  (Timed out)
ERROR: /home/WORKSPACE:16:9: fetching pip_repository rule //external:pip_gpu_cuda12_torch: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/f93b59b2e8d1062ff73145ba826f8efd/external/rules_python/python/pip_install/pip_repository.bzl", line 65, column 13, in _pip_repository_impl
                fail("rules_python_external failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: rules_python_external failed:  (Timed out)
ERROR: Skipping '//maga_transformer:maga_transformer': no such package '@pip_gpu_cuda12_torch//': rules_python_external failed:  (Timed out)
WARNING: Target pattern parsing failed.
ERROR: no such package '@pip_gpu_cuda12_torch//': rules_python_external failed:  (Timed out)
INFO: Elapsed time: 600.135s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: maga_transformer
构建时失败，已经添加了pip的镜像地址，还是time out, 请问还能怎么解决呢？而且我是cuda11的环境，不需要pip_gpu_cuda12_torch的包吧

**Comment by cwlseu** [comment]
同样的问题，直接编译有问题，还是直接安装whl包吧

**Comment by samaritan1998** [comment]
> 同样的问题，直接编译有问题，还是直接安装whl包吧

但是我需要添加别的模型^O^  应该是需要源码构建吧

**Comment by cwlseu** [comment]
@ySingularity

**Comment by ySingularity** [comment]
现在是先load两个版本的依赖之后再根据cuda版本选择，可以考虑用docker试试
https://github.com/alibaba/rtp-llm/blob/main/docs/DeployDocker.md

**Comment by samaritan1998** [comment]
> 现在是先load两个版本的依赖之后再根据cuda版本选择，可以考虑用docker试试 https://github.com/alibaba/rtp-llm/blob/main/docs/DeployDocker.md

现在就是用的docker环境

**Comment by ySingularity** [comment]
那手动删掉这个依赖试试？

**Comment by ySingularity** [comment]
此外也有可能是torch下载过慢，可以尝试构建时加入超时选项参数或者手动安装

**Comment by samaritan1998** [comment]
> 手动安装
手动安装是怎么安装呢

**Comment by ySingularity** [comment]
https://github.com/alibaba/rtp-llm/blob/main/open_source/deps/requirements_torch_gpu.txt
手动装一下pytorch，然后把requirement这部分注释掉

**Comment by samaritan1998** [comment]
成功了，感谢
