### ISSUE TITLE
bazel构建成功，但是测试报错

### ISSUE THREAD

**Issue by samaritan1998** [alibaba/rtp-llm#44]
报错信息：+---------------+---------------------+
[root][03/29/2024 06:38:30][decoder_engine.py:__init__():27][INFO] last mem info:41430286336 1074987008
[root][03/29/2024 06:38:30][stream_cache_manager.py:set_ptuning():32][INFO] reuse_cache: False
[root][03/29/2024 06:38:30][stream_cache_manager.py:set_ptuning():33][INFO] block_num after Ptuning: 4810
[root][03/29/2024 06:38:30][pipeline_custom_func.py:get_custom_func():34][INFO] using modify_prompt_plugin default implement
[root][03/29/2024 06:38:30][pipeline_custom_func.py:get_custom_func():28][INFO] using multimodal_modify_prompt_plugin implement in model
[root][03/29/2024 06:38:30][pipeline_custom_func.py:get_custom_func():28][INFO] using process_encode_plugin implement in model
[root][03/29/2024 06:38:30][pipeline_custom_func.py:get_custom_func():34][INFO] using process_decode_plugin default implement
[root][03/29/2024 06:38:30][pipeline_custom_func.py:get_custom_func():34][INFO] using modify_response_plugin default implement
[root][03/29/2024 06:38:30][pipeline_custom_func.py:get_custom_func():34][INFO] using stop_generate_plugin default implement
/opt/conda310/bin/python: symbol lookup error: /usr/local/lib/python3.10/dist-packages/torch/lib/libcudnn_cnn_infer.so.8: undefined symbol: _ZN15TracebackLoggerC1EPKc, version libcudnn_ops_infer.so.8

```
import os
from maga_transformer.pipeline import Pipeline
from maga_transformer.model_factory import ModelFactory, ModelConfig
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
model_name = "Qwen-VL"
model = ModelFactory.from_huggingface("/home/Qwen-VL/")
pipeline = Pipeline(model, model.tokenizer)
generate_config = {
    "top_k": 1,
    "max_new_tokens": 100
}
for res in pipeline("Picture 1:<img/>\n这是什么", images = ["/home/***.jpg"], generate_config = generate_config):
    print(res)
pipeline.stop()
```
但是使用python3 test.py单独运行是可以成功的，但是使用bazel test //example:test --jobs 100就是不行  ,使用的python解释器也是一样的

**Comment by baowendin** [comment]
由于bazel test时使用单独的LD_LIBRARY_PATH和python pip依赖，因此请检查这两项以排查问题

**Comment by samaritan1998** [comment]
请问bazel test是在哪里设置LD_LIBRARY_PATH和pip依赖的呢？pip依赖是通过pip.bzl安装的吧，LD_LIBRARY_PATH也是默认的配置

**Comment by samaritan1998** [comment]
查了一下 没啥问题啊 都是按照默认的配置 而且将Python执行时的LD_LIBRARY_PATH加进.bazelrc的LD_LIBRARY_PATH也是没有用 好奇怪 没有别人遇到过么
