### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by boxiaowave** [alibaba/rtp-llm#46]
使用medusa进行服务推理，服务能正常启动，但接收到请求后会出现以下报错导致服务挂掉退出：
maga_transformer/async_decoder_engine/medusa/medusa_model_executor.py", line 31, in _create_batch_query
    max_medusa_length = max([q.seq_length for q in batch_query.streams]) + validate_token_length
ValueError: max() arg is an empty sequence

打印[q.seq_length for q in batch_query.streams]发现是个空列表。使用0.1.8+cuda121的官方镜像，服务启动脚本为：
TP_SIZE=2 WORLD_SIZE=2 MAX_SEQ_LEN=16000 START_PORT=7301 TOKENIZER_PATH=/medusa/best CHECKPOINT_PATH=/medusa/best MODEL_TYPE=llama FT_SERVER_TEST=1 python3 -m maga_transformer.start_server
使用单机双卡推理，单卡推理会有oom报错，故没有在单卡下测试。

**Comment by jianglan89** [comment]
> 使用medusa进行服务推理，服务能正常启动，但接收到请求后会出现以下报错导致服务挂掉退出： maga_transformer/async_decoder_engine/medusa/medusa_model_executor.py", line 31, in _create_batch_query max_medusa_length = max([q.seq_length for q in batch_query.streams]) + validate_token_length ValueError: max() arg is an empty sequence
> 
> 打印[q.seq_length for q in batch_query.streams]发现是个空列表。使用0.1.8+cuda121的官方镜像，服务启动脚本为： TP_SIZE=2 WORLD_SIZE=2 MAX_SEQ_LEN=16000 START_PORT=7301 TOKENIZER_PATH=/medusa/best CHECKPOINT_PATH=/medusa/best MODEL_TYPE=llama FT_SERVER_TEST=1 python3 -m maga_transformer.start_server 使用单机双卡推理，单卡推理会有oom报错，故没有在单卡下测试。

medusa 暂时不支持分TP

**Comment by boxiaowave** [comment]
> > 使用medusa进行服务推理，服务能正常启动，但接收到请求后会出现以下报错导致服务挂掉退出： maga_transformer/async_decoder_engine/medusa/medusa_model_executor.py", line 31, in _create_batch_query max_medusa_length = max([q.seq_length for q in batch_query.streams]) + validate_token_length ValueError: max() arg is an empty sequence
> > 打印[q.seq_length for q in batch_query.streams]发现是个空列表。使用0.1.8+cuda121的官方镜像，服务启动脚本为： TP_SIZE=2 WORLD_SIZE=2 MAX_SEQ_LEN=16000 START_PORT=7301 TOKENIZER_PATH=/medusa/best CHECKPOINT_PATH=/medusa/best MODEL_TYPE=llama FT_SERVER_TEST=1 python3 -m maga_transformer.start_server 使用单机双卡推理，单卡推理会有oom报错，故没有在单卡下测试。
> 
> medusa 暂时不支持分TP

有后续的支持计划吗？

**Comment by jianglan89** [comment]
> > > 使用medusa进行服务推理，服务能正常启动，但接收到请求后会出现以下报错导致服务挂掉退出： maga_transformer/async_decoder_engine/medusa/medusa_model_executor.py", line 31, in _create_batch_query max_medusa_length = max([q.seq_length for q in batch_query.streams]) + validate_token_length ValueError: max() arg is an empty sequence
> > > 打印[q.seq_length for q in batch_query.streams]发现是个空列表。使用0.1.8+cuda121的官方镜像，服务启动脚本为： TP_SIZE=2 WORLD_SIZE=2 MAX_SEQ_LEN=16000 START_PORT=7301 TOKENIZER_PATH=/medusa/best CHECKPOINT_PATH=/medusa/best MODEL_TYPE=llama FT_SERVER_TEST=1 python3 -m maga_transformer.start_server 使用单机双卡推理，单卡推理会有oom报错，故没有在单卡下测试。
> > 
> > 
> > medusa 暂时不支持分TP
> 
> 有后续的支持计划吗？

暂时还没计划

**Comment by boxiaowave** [comment]
> > > > 使用medusa进行服务推理，服务能正常启动，但接收到请求后会出现以下报错导致服务挂掉退出： maga_transformer/async_decoder_engine/medusa/medusa_model_executor.py", line 31, in _create_batch_query max_medusa_length = max([q.seq_length for q in batch_query.streams]) + validate_token_length ValueError: max() arg is an empty sequence
> > > > 打印[q.seq_length for q in batch_query.streams]发现是个空列表。使用0.1.8+cuda121的官方镜像，服务启动脚本为： TP_SIZE=2 WORLD_SIZE=2 MAX_SEQ_LEN=16000 START_PORT=7301 TOKENIZER_PATH=/medusa/best CHECKPOINT_PATH=/medusa/best MODEL_TYPE=llama FT_SERVER_TEST=1 python3 -m maga_transformer.start_server 使用单机双卡推理，单卡推理会有oom报错，故没有在单卡下测试。
> > > 
> > > 
> > > medusa 暂时不支持分TP
> > 
> > 
> > 有后续的支持计划吗？
> 
> 暂时还没计划

好的，感谢回复
