### ISSUE TITLE
请问src/fastertransformer/models/multi_gpu_gpt/ParallelAttentionWrapper.cc的ContextAttention是什么概念呢？和SelfAttention有什么区别呢

### ISSUE THREAD

**Issue by samaritan1998** [alibaba/rtp-llm#49]

**Comment by netaddi** [comment]
Hi there,
During the forward function in attention layer, requests for initial token (aka. prompt processing) and next token decoding are batched together. ContextAttention computes multi-head attention for prompt processing, while SelfAttention computes mha for incremental tokens. They share basically the same compuation logic, but adopted different kernels for optimal performance under each case.

**Comment by samaritan1998** [comment]
get,  thanks
