### ISSUE TITLE
多卡推理

### ISSUE THREAD

**Issue by Vincent131499** [alibaba/rtp-llm#51]
在tp=2的时候推理正常，但tp>=4(tp=4 tp=8)的时候会报错。
验证模型：
1.qwen-1.5-14b-chat
2.qwen-1.5-32b-chat
3.llama2-70b-chat:https://hf-mirror.com/NousResearch/Llama-2-70b-chat-hf
硬件：A100

服务启动：
TP_SIZE=4 WORLD_SIZE=4 CONCURRENCY_LIMIT=2 WEIGHT_TYPE=int8 INT8_KV_CACHE=1 MAX_SEQ_LEN=8192 REUSE_CACHE=1 ENABLE_FMHA=OFF TOKENIZER_PATH=/workspace/pretrained-models/llama2-70b-chat-hf-nousresearch/ CHECKPOINT_PATH=/workspace/pretrained-models/llama2-70b-chat-hf-nousresearch/ MODEL_TYPE=llama FT_SERVER_TEST=1 python3 -m maga_transformer.start_server

报错如下：
![image](https://github.com/alibaba/rtp-llm/assets/26675984/fcde0801-3040-4559-baf2-ebbdfa2654a1)

**Comment by baowendin** [comment]
目前我们在A800和A10上针对qwen尝试复现，均未成功。
0.1.12优化了集合通信部分的日志输出，能麻烦升级到0.1.12后，在原有命令上添加环境变量FT_SERVER_TEST=1 NCCL_DEBUG=INFO，并提供所有的日志呢

**Comment by Vincent131499** [comment]
可以的，0.1.12的docker发版了吗，我直接pull下来测试

**Comment by baowendin** [comment]
0.1.12已经发布了

**Comment by Vincent131499** [comment]
ok 我docker pull测试下

**Comment by Vincent131499** [comment]
我使用0.1.12的docker启动容器，测试了qwen1.5-14b-chat
tp=2.可以正常请求，日志如下：
[tp2.log](https://github.com/alibaba/rtp-llm/files/15058264/tp2.log)
tp=4,可以部署服务，但是一请求就报错，日志如下：
[tp4.log](https://github.com/alibaba/rtp-llm/files/15058267/tp4.log)

麻烦帮忙检查下啊，是我机器环境的问题吗

**Comment by Vincent131499** [comment]
good!
配置RESERVER_RUNTIME_MEM_MB=10000这个tp=4可以正常请求了；
但是有2个疑问：
1.tp=2，使用同样的参数部署服务就可以正常请求，为何tp=4需要再额外配置这个参数呢？
2.这个参数RESERVER_RUNTIME_MEM_MB=10000的含义具体是什么意思呢？

**Comment by baowendin** [comment]
reserve_mem_mb含义：默认我们会把加载模型后所有显卡剩余的显存用于分配kvcache，仅留下1000mb作为runtime显存，用于在python层分配torch cuda tensor等
4tp挂掉的原因应该是world_size变大以后集合通信需要的显存也变多了，默认设置的1000mb不够
