### ISSUE TITLE
Remove print statements

### ISSUE THREAD

**Issue by mrchi** [alibaba/rtp-llm#55]
Such as:

https://github.com/alibaba/rtp-llm/blob/ce077e222581a94836b67e9065660cf24dedfbf3/maga_transformer/openai/renderers/qwen_renderer.py#L138

When the input is a multi-line string, the print statement outputs multiple lines, which is not elegant.

Could we use logging instead of print?

**Comment by netaddi** [comment]
This is a debug print and should be removed. thanks for reminding.
