### ISSUE TITLE
多卡部署空闲但导致的其他模型速度降低很多

### ISSUE THREAD

**Issue by invisifire** [alibaba/rtp-llm#64]
![image](https://github.com/alibaba/rtp-llm/assets/59678894/cc89780f-1975-4e97-bccc-80fcabf41e71)
如图 ,部署了3个模型,
使用TP=1时无论起多少个互不干扰生成速度, 但是当使用了TP=2, 会导致显示沾满的显卡速度从70token/s降低至30token/s 并发下下降幅度基本类似 , 有解决方案吗?还是说是nccl导致的没办法解决

**Comment by invisifire** [comment]
若把模型从cuda1设备移至cuda0则速度就不受影响

**Comment by netaddi** [comment]
Hi,
We are not sure about what caused the slowing down of generation, but in general running multiple models on a single card is not an expected usage.
If that's the case, using nvidia MIG might be a possible solution.
