### ISSUE TITLE
Does it support Qwen2、ChatGLM4-9B?

### ISSUE THREAD

**Issue by ZCDu** [alibaba/rtp-llm#65]

**Comment by netaddi** [comment]
Hi,
qwen2 is already supported, and we are working on GLM4 support.

**Comment by netaddi** [comment]
update:
GLM4 is also naturally supported, but openai api suffer from incorrect prompt rendering.
We have fixed it and expect to release it in the upcoming version.

**Comment by samaritan1998** [comment]
> update: GLM4 is also naturally supported, but openai api suffer from incorrect prompt rendering. We have fixed it and expect to release it in the upcoming version.

config.special_tokens.eos_token_id = config_json['eos_token_id']  加载配置文件这里会报错,  chatglmv3是int值, glm4变成数组了
