### ISSUE TITLE
请问multimodel_mixin.py中BaseMultiModalWeightInfo的_get_vit_info函数中self.vit_weights？ 

### ISSUE THREAD

**Issue by samaritan1998** [alibaba/rtp-llm#67]
或许可以支持一下self.vit_weights为数组么？   想提一个PR（实现了Vary），不知道是否可以改动这里

**Comment by ySingularity** [comment]
BaseVitWeights本身就支持list格式的tensor name，想问一下大概是什么场景下需要

**Comment by samaritan1998** [comment]
好像是不支持的，比如Vary模型，我需要定义这样一个权重List
![image](https://github.com/alibaba/rtp-llm/assets/48083986/e34b07b4-5a3e-4673-8ccb-f0d76821c4a1)

**Comment by samaritan1998** [comment]
Vary有两个图像编码器

**Comment by ySingularity** [comment]
是因为tensor prefix不一样所以需要定义四个VitWeight类吗；用VitWeight类的成员函数去定义这个行为会不会改动简单点

**Comment by samaritan1998** [comment]
是因为prefix不一样 我再看下吧

**Comment by samaritan1998** [comment]
![image](https://github.com/alibaba/rtp-llm/assets/48083986/604a7239-5747-48e3-a79c-bc2fbe315799)
可是这个结构就需要prefix一样吧，不太明白您说的意思:)

**Comment by ySingularity** [comment]
在BaseVitWeights._get_vit_params里根据key加入不同前缀，_ckpt_prefix置空即可

**Comment by samaritan1998** [comment]
okk 感谢
