### ISSUE TITLE
v0.1.13 load qwen2 gptq失败

### ISSUE THREAD

**Issue by xinge666** [alibaba/rtp-llm#68]
gpu: A100
镜像：registry.cn-hangzhou.aliyuncs.com/havenask/rtp_llm:0.1.13_cuda11
cuda:  Driver Version: 535.104.12   CUDA Version: 12.2

测试代码如下：
import os 
os.environ['TP_SIZE'] = '2'
os.environ['WORLD_SIZE'] = '2'

os.environ.get('TP_SIZE', '1')
from maga_transformer.pipeline import Pipeline
from maga_transformer.model_factory import ModelFactory

model = ModelFactory.from_huggingface("./Qwen1.5-72B-Chat-GPTQ-Int4/")
pipeline = Pipeline(model, model.tokenizer)
for res in pipeline("<|im_start|>user\nhello, what's your name<|im_end|>\n<|im_start|>assistant\n", max_new_tokens = 100):
    print(res.generate_texts)
pipeline.stop()

报错信息如下
![image](https://github.com/alibaba/rtp-llm/assets/28565278/1c0567d1-e2d1-4185-a7a4-a4377d6c25cf)

采用命令行启动 多卡出现问题（单卡正常部署）
单卡命令如下
TART_PORT=18096 TOKENIZER_PATH=/data0/models/qwen2/Qwen2-72B-Instruct-GPTQ-Int4/ CHECKPOINT_PATH=/data0/models/qwen2//Qwen2-72B-Instruct-GPTQ-Int4/ MODEL_TYPE=qwen_2  FT_SERVER_TEST=1 NCCL_DEBUG=INFO python3 -m maga_transformer.start_server
多卡命令如下
TP_SIZE=4 WORLD_SIZE=4 START_PORT=18096 TOKENIZER_PATH=./Qwen2-72B-Instruct-GPTQ-Int4/ CHECKPOINT_PATH=./Qwen2-72B-Instruct-GPTQ-Int4/ MODEL_TYPE=qwen_2  FT_SERVER_TEST=1 python3 -m maga_transformer.start_server
报错如下 Bus error: nonexistent physical address
![image](https://github.com/alibaba/rtp-llm/assets/28565278/30d30aa2-fe74-411e-9814-3efcad14e217)

另外，有一个加载耗时问题，每次加载都要耗时 5min左右，cpu占用都是满的，这是正常的吗？有办法缩短吗？
辛苦大佬看下，不胜感激

**Comment by dongjiyingdjy** [comment]
应该是/dev/shm太小了，试试进docker配置更大的--shm-size

**Comment by xinge666** [comment]
> 应该是/dev/shm太小了，试试进docker配置更大的--shm-size

已解决，谢谢大佬
