### ISSUE TITLE
ChatGLM4-9B运行不起来

### ISSUE THREAD

**Issue by samaritan1998** [alibaba/rtp-llm#69]
![image](https://github.com/alibaba/rtp-llm/assets/48083986/17f77e6e-2728-4de8-9c9a-4c158c9e5ba1)
glm4-9b运行不起来，export MODEL_TYPE=chatglm3
export CHECKPOINT_PATH=/home/checkpoint/chatglm4/glm-4-9b
export TOKENIZER_PATH=/home/checkpoint/chatglm4/glm-4-9b    这是设置的环境变量，请问下这个适配了么，这个失败是什么原因呢？:)

**Comment by baowendin** [comment]
需要对齐tiktoken版本到0.7.0
