### ISSUE TITLE
有人测试成功过么？

### ISSUE THREAD

**Issue by liucw2012** [alibaba/rtp-llm#7]
ubuntu台式机测试，目前进展：
1. docker 方式需要pull 阿里的镜像仓库的镜像； fail
2.pip 文档明确待上传rtp-llm包；fail
3.源码构建，bazel 报错，issue: https://github.com/alibaba/rtp-llm/issues/6
有高人成功过么？

**Comment by xinfeishi** [comment]
1 请问拉取阿里的docker仓库是什么报错？可以贴一下错误的信息吗？
2 rtp-llm在上传了，我在更改文档了。
3 应该是remote cach的问题，我修改下。

**Comment by netaddi** [comment]
我build和运行可以成功。。环境为win10+wsl2，驱动版本545.23.06+cuda 12.3，直接在裸环境build，没有用docker。建议在/opt/conda310目录安装一个python。

**Comment by xinfeishi** [comment]
已经修复你说的几个问题，可以再试试。
