### ISSUE TITLE
编译报错  v0.2.0 版error: cannot convert ‘<brace-enclosed initializer list>’ to ‘const fastertransformer::AllGatherParams&’

### ISSUE THREAD

**Issue by invisifire** [alibaba/rtp-llm#70]
Use the official CUDA 12 image
Modify Bazel to version 5.2.0
After adding #include <mutex> according to the installation error prompt,
使用 官方镜像cuda12
修改bazel 至5.2.0 版本

因报错安装提示增加#include <mutex>后
![ce6da78ec2bd8c8bce4a5dc63eb3b1d](https://github.com/alibaba/rtp-llm/assets/59678894/515b674a-d435-41e8-8a43-a1a7aa57237f)

The compilation continues to report errors.
编译继续报错
![817b08bc7cd203c8fa9f8668ac61240](https://github.com/alibaba/rtp-llm/assets/59678894/3a22b411-c2f0-41c6-bc7d-36da2dee0aca)

The CUDA version and GCC version are as follows:
cuda版本 和 gcc版本如下

![042164c18d9ccc9372856019388665d](https://github.com/alibaba/rtp-llm/assets/59678894/61667028-4aa6-4a32-b338-fb6e796b92a2)

**Comment by samaritan1998** [comment]
遇到了同样的问题

**Comment by xinfeishi** [comment]
你这个gcc咋报 std::unique_lock 找不到呢？
我来复现下吧。

**Comment by invisifire** [comment]
> 你这个gcc咋报 std::unique_lock 找不到呢？ 我来复现下吧。

使用官方提供的 cuda12 镜像 , clone本项目到本地, 降级bazel为5.2.0 , 设置pip超时10000秒, 然后直接运行命令
bazel build //maga_transformer:maga_transformer --jobs 100 --verbose_failures --config=cuda12_2

**Comment by invisifire** [comment]
> 你这个gcc咋报 std::unique_lock 找不到呢？ 我来复现下吧。

我目前降级gcc为10.5就会报另一个错误
ERROR: /home/dev/.cache/bazel/_bazel_dev/94ec30666e7a680173052746412c29d4/external/com_google_absl/absl/base/BUILD.bazel:54:11: Compiling absl/base/log_severity.cc failed: The include path '/usr/lib/gcc/x86_64-linux-gnu/10/include' references a path outside of the execution root.
ERROR: /home/dev/.cache/bazel/_bazel_dev/94ec30666e7a680173052746412c29d4/external/com_google_absl/absl/types/BUILD.bazel:166:11: Compiling absl/types/bad_variant_access.cc failed: The include path '/usr/lib/gcc/x86_64-linux-gnu/10/include' references a path outside of the execution root.
ERROR: /home/dev/.cache/bazel/_bazel_dev/94ec30666e7a680173052746412c29d4/external/com_google_absl/absl/numeric/BUILD.bazel:27:11: Compiling absl/numeric/int128.cc failed: The include path '/usr/lib/gcc/x86_64-linux-gnu/10/include' references a path outside of the execution root.
Target //maga_transformer:maga_transformer failed to build
INFO: Elapsed time: 4.628s, Critical Path: 0.17s
INFO: 154 processes: 153 internal, 1 local.
FAILED: Build did NOT complete successfully
include失败

**Comment by samaritan1998** [comment]
gcc也是镜像里自带的

**Comment by samaritan1998** [comment]
![image](https://github.com/alibaba/rtp-llm/assets/48083986/cfa4d7f6-8782-428c-8989-3c4d3574f71a)

**Comment by samaritan1998** [comment]
> 你这个gcc咋报 std::unique_lock 找不到呢？ 我来复现下吧。

请问有复现出来么？

**Comment by samaritan1998** [comment]
![image](https://github.com/alibaba/rtp-llm/assets/48083986/54cdc704-3c6e-4480-9a3b-d11e9612bf0c)
按照这个改了之后就可以了

**Comment by xinfeishi** [comment]
> ![image](https://private-user-images.githubusercontent.com/48083986/344560007-54cdc704-3c6e-4480-9a3b-d11e9612bf0c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTQ5MzksIm5iZiI6MTcxOTgxNDYzOSwicGF0aCI6Ii80ODA4Mzk4Ni8zNDQ1NjAwMDctNTRjZGM3MDQtM2M2ZS00NDgwLTlhM2ItZDExZTk2MTJiZjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA2MTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkNjIwMzBlNmRjMDEyZjdiODg3YmE1ZmI5YmI3YjY2N2YyZjUwNWVjOWM3NjFlMzdlOTlmMzVhYjJiNWExYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nSUOp1bKaFDiPv7khUluYYDvAFzRaCJTNNsTHqtn58M) 按照这个改了之后就可以了

那我在我们的项目中修改下。
