### ISSUE TITLE
glm4v 单卡Cuda out of memory 

### ISSUE THREAD

**Issue by samaritan1998** [alibaba/rtp-llm#73]
![image](https://github.com/alibaba/rtp-llm/assets/48083986/246731bd-75cf-405d-86f6-5debc23d8be2)
按照图上的内存要求，应该是可以部起来的吧，但是Cuda out of memory 了

**Comment by xiaoyong-z** [comment]
这边统计内存的地方存在一些BUG，没有把glm4v的VIT部分记录在里面，可以将WEIGHT_TYPE设置为INT8试试
