### ISSUE TITLE
Glm4v运行问题

### ISSUE THREAD

**Issue by samaritan1998** [alibaba/rtp-llm#75]

**Comment by samaritan1998** [comment]
环境信息：cuda 12.2  Cuda:12.2 ，使用官方镜像，安装0.2.0的whl包

执行TP_SIZE=2 WORLD_SIZE=2 TOKENIZER_PATH=/home/glm-4v-9b CHECKPOINT_PATH=/home/glm-4v-9b MODEL_TYPE=chatglm4v FT_SERVER_TEST=1 python3 -m maga_transformer.start_server    
（双卡部署）

然后执行Curl命令，含图片时报错：
curl -XPOST http://localhost:8088/ -d '{"prompt":"给出图像中的结构化信息","images":["****"],"generate_config":{"max_new_tokens":1000}}'

报错信息：
/usr/local/lib/python3.10/dist-packages/maga_transformer/models/multimodal_mixin.py", line 151, in process_multimodel_input_func\n    raise NotImplementedError()\nNotImplementedError\n

然后我在chat_glm_v4_vision.py里加了process_multimodel_input_func这个函数（copy了Llava里的），然后不报错了，但是回答和图片没有关联

**Comment by xiaoyong-z** [comment]
process_multimodel_input_func可以直接从Llava拷贝，在下次代码同步的时候应该就会修复。

回答和图片没有关联是因为glm4v有自己的prompt template格式，可以参考maga_transformer/openai/renderers/chatglm4_renderer.py

在maga_transformer的实现中，我们只在openai格式的请求增加了这种prompt template，因此解决方法有两个:
1. 将原来的请求格式改成openai格式，见https://github.com/alibaba/rtp-llm/blob/main/docs/OpenAI-Tutorial.md
2. 继续使用原来的格式，但需要自己将prompt render成glm4v所要求的格式。

**Comment by samaritan1998** [comment]
okk 我也发现了 感谢
