### ISSUE TITLE
git clone Error

### ISSUE THREAD

**Issue by hz0ne** [alibaba/rtp-llm#78]
When I clone repo, git lfs notify the `This repository is over its data quota. ` Error, and **break** the cloning process.
Plz check the necessary file sizes and fix quota.

Error detail:
```
$ git-lfs filter-process
Error downloading object: maga_transformer/models/test/testdata/llama/AquilaChat2-7B/pytorch_model.bin (30e2f24): Smudge error: Error downloading maga_transformer/models/test/testdata/llama/AquilaChat2-7B/pytorch_model.bin (30e2f243cf6380041d865181f71f9d1d270162b1b712c06fed66cd5aee50d332): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

**Comment by ySingularity** [comment]
We will fix it later. You can skip lfs download for now, as most of these files are used for testing.

**Comment by khan-yin** [comment]
the same problem I got

**Comment by TianyuLi0** [comment]
Workaround for skipping lfs download: `git lfs install --skip-smudge`

Reference
https://stackoverflow.com/questions/42019529/how-to-clone-pull-a-git-repository-ignoring-lfs
