### ISSUE TITLE
使用离线方式安装 导入包运行example报错

### ISSUE THREAD

**Issue by JadeLuo** [alibaba/rtp-llm#8]
python3 example/test.py 
Traceback (most recent call last):
  File "/tmp/test.py", line 7, in <module>
    from maga_transformer.inference import InferenceWorker
ImportError: bad magic number in 'maga_transformer': b'o\r\r\n'

Python 3.11.5
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

anyio==4.2.0
certifi==2023.11.17
charset-normalizer==3.3.2
click==8.1.7
contourpy==1.2.0
cpm-kernels==1.0.11
cycler==0.12.1
dacite==1.8.1
einops==0.7.0
fastapi==0.95.0
filelock==3.13.1
fonttools==4.47.0
fsspec==2023.12.2
h11==0.14.0
huggingface-hub==0.20.1
idna==3.6
importlib-metadata==7.0.1
Jinja2==3.1.2
kiwisolver==1.4.5
lru-dict==1.3.0
maga_transformer @ file:///data/works/rtp-llm/maga_transformer-0.1.0-py3-none-any.whl#sha256=cb4758057e849822f29f41ec79184ca2c088888a4379b43e6d53a746a8bc754d
MarkupSafe==2.1.3
matplotlib==3.8.2
mpmath==1.3.0
networkx==3.2.1
numpy==1.24.1
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
packaging==23.2
pillow==10.2.0
protobuf==3.20.0
psutil==5.9.7
py-spy==0.3.14
pydantic==1.10.13
pynvml==11.5.0
pyodps==0.11.4.1
pyparsing==3.1.1
python-dateutil==2.8.2
PyYAML==6.0.1
regex==2023.12.25
requests==2.31.0
safetensors==0.4.1
sentencepiece==0.1.99
six==1.16.0
sniffio==1.3.0
starlette==0.26.1
sympy==1.12
thrift==0.16.0
tiktoken==0.4.0
tokenizers==0.13.3
torch==2.1.0
torchvision==0.16.0
tqdm==4.66.1
transformers==4.33.1
triton==2.1.0
typing_extensions==4.9.0
urllib3==1.26.18
uvicorn==0.21.1
zipp==3.17.0

**Comment by xinfeishi** [comment]
使用我们提供的开发docker，可以使用python3.10 来运行。3.11我试一下看看。

**Comment by xinfeishi** [comment]
3.11看起来就是不兼容的，所以还是需要使用3.10的python来安装whl。
